name: Deploy to Synology NAS via SSH (rsync + PM2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ SSH 비밀키 설정
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.NAS_SSH_KEY }}

      # 3️⃣ NAS 호스트 키 등록
      - name: Add NAS host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.NAS_IP }} >> ~/.ssh/known_hosts

      # 4️⃣ NAS에 파일 복사 (rsync, node_modules 제외, 권한 설정 무시)
      - name: Rsync to Synology NAS
        run: |
          rsync -avz --no-perms \
            --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --ignore-errors \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ admin@${{ secrets.NAS_IP }}:/volume1/web/myweb/

      #
