name: Deploy to Synology NAS via SSH (rsync + PM2)
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. SSH 비밀키 설정
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. NAS에 파일 복사
      - name: Rsync to Synology NAS
        run: |
          rsync -avz --delete --exclude='.git' ./ deploy@NAS_IP:/volume1/web/myweb/

      # 4. NAS에서 PM2 재시작
      - name: Restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no deploy@NAS_IP << 'EOF'
            cd /volume1/web/myweb
            npm install
            pm2 restart all
            pm2 save
          EOF
